##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end

Vagrant.configure("2") do |config|

    # Config
    env_prefix  = ENV['DRUPAL_VAGRANT_ENV_PREFIX'] || 'DRUPAL_VAGRANT'
    ip          = ENV["#{env_prefix}_IP"] || '10.33.36.13'
    project     = ENV["#{env_prefix}_PROJECT"] || 'piper'
    #End config

    config.vm.box = "aczietlow/pandoras-box"
    path = "/var/www/#{project}.dev"

    config.vm.synced_folder ".", "/vagrant", :disabled => true
    config.vm.synced_folder ".", path, :nfs => true
    config.vm.hostname = "#{project}.dev"

    config.vm.network "private_network", ip: "#{ip}"
    config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |v|
        v.name = "#{project}-box"
        v.customize [
            "modifyvm", :id,
            "--name", "#{project}",
            "--memory", 2048,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.provider "vmware_fusion" do |v|
        v.name = "#{project}-box"
        v.gui = false
        v.vmx["memsize"] = "2048"
    end

    config.vm.provision :shell, inline: <<SCRIPT
    set -ex
    if [[ ! -f "#{path}/cnf/settings.php" ]]; then
        su vagrant -c "cp #{path}/cnf/local.settings.php #{path}/cnf/settings.php;"
    fi
    /usr/local/phantomjs --webdriver=8643 &> /dev/null &
    su vagrant -c 'cd #{path} && composer install;
    echo #{path}
    cd #{path} && [[ -f .env ]] && source .env || cp env.dist .env && source env.dist && build/install.sh;'
SCRIPT

end
